apiVersion: v1
kind: Service
metadata:
  name: ornithology
  labels:
    app: ornithology
    production: ready
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
      app: ornithology
      production: ready
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ornithology
spec:
  replicas: 9
  template:
    metadata:
      labels:
        app: ornithology
        production: ready
    spec:
      containers:
      - name: ornithology
        image: otomato/ornithology:BUILD_NUMBER
        ports:
        - containerPort: 5000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
